### ISSUE TITLE
好像并没有解决花屏的问题。请求回来的m3u8链接，下载后还是会花屏。

### ISSUE THREAD

**Issue by PhilipsYuan** [fyu0h/cctv_downloader_web#1]
还是有花屏的问题
demo链接： https://app.cctv.com/special/m/livevod/index.html?vtype=2&guid=70c89802f5c3421282f1d2252e8386f6&vsetId=C10616

**Comment by fyu0h** [comment]
6月1日更新了加密，只能用猫抓之类的插件缓存捕捉了

**Comment by fyu0h** [comment]
![image](https://github.com/fyu0h/cctv_downloader_web/assets/33602841/188fef2f-a630-4075-8133-990187a3ce6b)
我这边测试了下你给的链接，能下载到低分辨率的视频，6月1日更新加密后这个办法就只能获取到低清视频了。

**Comment by PhilipsYuan** [comment]
可否支持高清视频下载？

**Comment by fyu0h** [comment]
不行了

**Comment by PhilipsYuan** [comment]
发现一个可以解决高清的了，“小滑轮m3u8” 软件。 https://www.feiaci.com/xhl/m3u8Video

**Comment by fyu0h** [comment]
“小滑轮m3u8”是收费软件
推荐使用猫抓
https://chromewebstore.google.com/detail/%E7%8C%AB%E6%8A%93/jfedfbgedapdagkghmgibemcoggfppbb?hl=zh-CN
