### ISSUE TITLE
下载的视频不是超清

### ISSUE THREAD

**Issue by Dododu** [fyu0h/cctv_downloader_web#2]
下载的视频不是超清

**Comment by PhilipsYuan** [comment]
可以使用“小滑轮m3u8”， 它支持高清。 https://www.feiaci.com/xhl/m3u8Video

**Comment by fyu0h** [comment]
“小滑轮m3u8”是收费软件
推荐使用猫抓
https://chromewebstore.google.com/detail/%E7%8C%AB%E6%8A%93/jfedfbgedapdagkghmgibemcoggfppbb?hl=zh-CN
